POST http://localhost:4000/reports
Content-Type: application/json

{
    "make":"Honda",
    "model":"Civic",
    "year":2018,
    "mileage": 100000,
    "lng" : 0,
    "lat" : 0,
    "price": 20000
}

### Patch Req
PATCH http://localhost:4000/reports/1
Content-Type: application/json

{
    "approved": true
}


### Get an estimate for an existing vehicle
GET http://localhost:4000/reports?make=Honda&model=Civic&year=2018&mileage=100000&lng=0&lat=0
