### create a new user
POST  http://localhost:4000/auth/signup
Content-Type: application/json

{
    "email": "mhmd@gmail.com",
    "username": "mhmd10",
    "password":"1234567"
}

### Update a User
PATCH   http://localhost:4000/auth/4
Content-Type: application/json

{
    "age" : 10
  
}

### Remove a user
DELETE http://localhost:4000/auth/2


### Get a User
GET http://localhost:4000/auth/3


### Get all Users
GET http://localhost:4000/auth/

### Get by Email
GET http://localhost:4000/auth?email=mhmd2@gmail.com
