### create a new user
POST  http://localhost:4000/auth/signup
Content-Type: application/json

{
    "email": "ali7@gmail.com",
    "username": "ali7",
    "password":"123456",
    "age": 20
}

### login a user
POST  http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "ali7@gmail.com",
    "password" : "123456"
    
}


### Update a User
PATCH   http://localhost:4000/auth/8
Content-Type: application/json

{
    "age" : 10
  
}

### Remove a user
DELETE http://localhost:4000/auth/13


### Get a User
GET http://localhost:4000/auth/5


### Get all Users
GET http://localhost:4000/auth/

### Get by Email
GET http://localhost:4000/auth?email=mhmd2@gmail.com
